### PR TITLE
ci: migrate from focal to jammy, el8

### PR DESCRIPTION
**Pull request by garlick**
Problem: focal CI builds are failing.

There seems to be a linkage problem with libjansson in the fluxrm/flux-core:focal image.

Move most focal builders to jammy.

There seems to be a problem with the configure script generated for ompi 2.x and 3.x in jammy:
```
checking for struct sockaddr_in... yes
checking if --with-cuda is set... not set (--with-cuda=) ./configure: line 13031: syntax error near unexpected token `)'
./configure: line 13031: `    )'
```
Move those builders to el8.

Tidy up builder descriptions.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
LGTM, but is there an issue to be investigated in the flux-core focal image?

Also, should the `src/test/docker/focal` directory be removed by this PR?

**Comment by garlick** [comment]
I'll fix this to remove focal and also open a flux-core issue on the image

**Comment by garlick** [comment]
CI seems confused by my retitling tests - I think it's waiting for the old test names to report in.  I'll just manually merge this.
Thanks for the review.

**Comment by grondo** [comment]
You may have to update branch protections. (Settings -> Branches -> Update branch protections)

**Comment by garlick** [comment]
Oh yes, thank you!

**Pull request merged**
