### PR TITLE
build: fix build with gcc 4.x, add centos7 to ci

### PR DESCRIPTION
**Pull request by grondo**
This PR fixes the compilation problem described in #47, and adds a gcc 4.x build via a new centos7 builder in CI.

Edit: This PR also adds a bionic Dockerfile, but does not use it in CI due to an outstanding segfault on that platform. (Will open issue)

### CODE REVIEW

**Review by garlick — APPROVED** [review]
LGTM!  Thanks for working through these issues!

**Comment by grondo** [comment]
Had to restart the workflow because mvapich2 failed to download (centos8 builder has to download and configure mvapich2 in order to uninstall it :roll_eyes:)

**Comment by grondo** [comment]
Oops, I forgot that `.mergify.yml` would have to be updated since the name of a builder changed.

I pushed that change here, but that means the PR will need to be manually merged.

The mergify config also needs to be updated to use queues instead of strict merge. I'll do that in a separate PR unless you'd rather me just do it here since this needs manual merge anyway.

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
