### PR TITLE
testsuite: add small test programs and sharness test

### PR DESCRIPTION
**Pull request by garlick**
This adds some test programs:
- the simple mpi tests from flux-core, `hello`, `version`, `abort`
- two new ones `barrier` and `bizcard` that are programmed directly against the pmix client api

Sharness framework is pulled in and one test is added that verifies that the configured ompi/pmix can launch the test programs.
This is as a precursor to testing whether flux can do it, with the new plugin.

### CODE REVIEW

**Comment by grondo** [comment]
Need any help setting up Github Actions/CI?

**Comment by garlick** [comment]
Any help would be great!  Would appreciate a pr or just general advice - whatever works best for you.

**Comment by grondo** [comment]
I'll develop something on top of this PR so that the tests you are pushing get run

**Comment by grondo** [comment]
Suggestion: Move the test-only programs under `t/src` instead of `src/test` to match other flux-framework projects. For better or worse, our standard suite of ci tools live under `src/test` e.g. `src/test/checks_run.sh` and `src/test/docker/*`...

**Comment by garlick** [comment]
Re-pushed with test programs located under `t/src`.

**Comment by garlick** [comment]
Rebased on master after merge of #4.

**Review by grondo — APPROVED** [review]
LGTM! Feel free to set MWP when ready.

**Comment by grondo** [comment]
@mergifyio refresh

**Comment by grondo** [comment]
Ok Mergify doesn't want to see the fixed config file, but I'll go ahead and merge and hopefully it will work in the next PR.

**Comment by garlick** [comment]
Thanks!

**Pull request merged**
